sudo: false
os:
  - linux

language: rust
rust:
    - stable
    - beta
    - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - RUST_BACKTRACE=1
    - RUST_TEST_THREADS=1
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
